### ISSUE TITLE
Issues with search

### ISSUE THREAD

**Issue by pederjohnsen** [mervick/emojionearea#200] opened 2017-11-06 15:58 UTC
After my changes we've noticed a couple of issues.
- [x] 1. Searching for random junk text like `awefpokawpe` then changing skin tone suddenly returns non-matching emojis.
![https://i.imgur.com/L8IhS46.png?1](https://i.imgur.com/L8IhS46.png?1)
- [x] 2. Before any emojis are loaded into cache, searching for example `thumb` then changing skin tone, and removing the text you're left with emojis not showing until you scroll or change skin tones again.
![https://i.imgur.com/ev8SqBk.png?1](https://i.imgur.com/ev8SqBk.png?1)

I'll look at these issues sometime over the next couple days, if you guys have any thoughts do share :)

**Comment by carpii** [comment] 2017-11-07 00:49
@pederjohnsen Only had a brief look at this, I'll try to find time to look further

But my hunch is, it might be worth refactoring the "@search.keypress" handler out into a separate function.

Then just call this at the end of the "@filter.click" and "@tone.click" handlers

**Comment by pederjohnsen** [comment] 2017-11-07 09:26
@carpii yeah I think this makes sense, as atm it only hides/shows full categories for the tone that is active, so when changing tone we'd want to trigger that again. Giving it a look now :+1:

**Comment by pederjohnsen** [comment] 2017-11-07 09:34
Seems we can just run `self.trigger('search.keypress');` :100:

**Comment by johnsenpeder** [comment] 2017-11-24 09:36
Number 2 seems to have been re-introduced with one of the latest changes?

It happens when you remove the search text quick, or in one go by selecting it then deleting the text.

**Comment by pederjohnsen** [comment] 2018-01-23 16:51
@mervick number 2 is still an issue with latest version, seems the changes here is to blame: https://github.com/mervick/emojionearea/blob/master/src/function/init.js#L447 `hide` will here be the search dom element (if picker is open) when the event is not manually triggered with first param as true. Which means the if statement here https://github.com/mervick/emojionearea/blob/master/src/function/init.js#L501 will always return false, as `hide` is set.

I guess perhaps we should consider updating the if statement to be `if (hide !== true)`

**Comment by mervick** [comment] 2018-01-23 21:08
@johnsenpeder I can't reproduce this, works well for me

**Comment by pederjohnsen** [comment] 2018-01-23 21:32
@mervick This screen recording shows the issue, using the jsfiddle of the latest version:
![emojis_not_loading_after_search](https://user-images.githubusercontent.com/1238485/35301882-b5563cd0-0084-11e8-8199-9b1083e6abe5.gif)

**Comment by bitaedalati** [comment] 2018-02-06 15:26
I had it too and fixed it by debounce function
"Creates a debounced function that delays invoking func until after wait milliseconds have elapsed since the last time the debounced function was invoked"

**Comment by carpii** [comment] 2018-02-09 21:53
@pederjohnsen is this still an issue on latest release - https://jsfiddle.net/mervick/1v03Lqnu/765/?

I cannot reproduce it either

**Comment by pederjohnsen** [comment] 2018-02-09 22:17
@carpii yeah, still present :confused:

**Comment by carpii** [comment] 2018-02-09 22:23
@pederjohnsen Ok thanks, I can reproduce it now too. But very occasionally it seems to work ok

**Comment by carpii** [comment] 2018-02-09 22:47
Fix pushed to searchfilter branch

Please could you test on this fiddle.. https://jsfiddle.net/1v03Lqnu/921/

**Comment by pederjohnsen** [comment] 2018-02-09 22:54
@carpii seems to fix it :+1:

**Comment by carpii** [comment] 2018-02-09 22:59
@mervick I intended to merge my 'searchfilter' branch into 'development' and then ask you to review that and merge into master

Instead I have merged it directly into master instead, sorry :(

**Comment by carpii** [comment] 2018-02-09 23:02
@pederjohnsen do you know where this event is fired when 'hide' param not be the search picker?  
It feels like we my be using the same param for two different purposes

**Comment by pederjohnsen** [comment] 2018-02-09 23:03
@carpii https://github.com/mervick/emojionearea/blob/dc73dc556fdc6e82c5d26847533b893ece255ce1/src/function/init.js#L455

**Comment by carpii** [comment] 2018-02-09 23:04
@pederjohnsen thanks, I will take a look. I will wait for @mervick for advice on master before making any more changes, I kinda messed up a bit :)

**Comment by mervick** [comment] 2018-02-10 03:09
Looks fine

**Closed by mervick** 2018-02-10 03:09 UTC
Labels: bug
