### ISSUE TITLE
On PageLoad i need display wrapper with all images

### ISSUE THREAD

**Issue by Nagaraj007** [mervick/emojionearea#132] opened 2017-05-16 05:54 UTC
Thanks for this plugin. I am using standalone emoji It works fine. Now i want to display it on page load,i need to open wrapper with images inside wrapper on page load.  I have wrote some code which display the  wrapper in open mode but images inside of it not displayed.
    $( document ).ready(function() {
     onPageload()
   });
    function onPageload()
   {
      // this code keep the wrapper open,But images not displayed
     $(".emojionearea").find(".emojionearea-standalone").addClass("focused");
    $(".emojionearea").find(".emojionearea-button").addClass("active");
    $(".emojionearea").find(".emojionearea-picker").removeClass("hidden");  
    }

**Comment by mervick** [comment] 2017-10-04 01:27
duplicate of https://github.com/mervick/emojionearea/issues/78

**Closed by mervick** 2017-10-04 01:27 UTC
Labels: enhancement
