### ISSUE TITLE
Use as a panel button in TinyMCE

### ISSUE THREAD

**Issue by harshal-shirude** [mervick/emojionearea#302] opened 2018-08-30 17:31 UTC
I am trying to use emojione-area as toolbar button in TinyMCE. I found [this](https://github.com/mervick/emojionearea/issues/280) thread which says use emojione-area in standalone mode and use click on emoji to insert into editor. But I am not able to use standalone version as a button in TinyMCE. Do we have any out of the box support to achieve the same?

**Comment by lasdeparq** [comment] 2018-08-31 13:32
@harshal-shirude 
You can create a custom-toolbar-button that on click will open emojioneArea standalone version. And you can position the emojioneArea with CSS as you wish.

**Comment by kthsu** [comment] 2018-11-13 12:17
@lasdeparq I am trying to implement your suggestion and could use a little help. Do you mean tie emojioneArea to the panel button directly or make the panel button open another UI (e.g. dialog) then attach emojioneArea?

Thanks for any help you can provide!

**Comment by mervick** [comment] 2018-12-05 22:00
duplicate of https://github.com/mervick/emojionearea/issues/235

**Closed by mervick** 2018-12-05 22:00 UTC
