### ISSUE TITLE
Pass an [contenteditable] directly

### ISSUE THREAD

**Issue by SaadeMotion** [mervick/emojionearea#103] opened 2017-02-07 01:19 UTC
Hi!, i was trying to figure it out, how to pass an already editable div to emojionearea. Since i'm using a WYSIWYG editor, it already makes my div "editable", the problem is that EmojioneArea, creates another [contenteditable] div inside my editable div.

How "standalone" option works?

**Comment by mervick** [comment] 2017-10-04 01:02
duplicate of https://github.com/mervick/emojionearea/issues/22

**Closed by mervick** 2017-10-04 01:02 UTC
Labels: duplicate
