### ISSUE TITLE
Clicking behind the editor, when editor is empty

### ISSUE THREAD

**Issue by Nixen85** [mervick/emojionearea#231] opened 2018-01-31 10:12 UTC
Hi, 

I`m trying to fix a problem that kind of drives me crazy. When I click next to the buttons in my textarea, the cursor is shown behind the editor or more precisely is is shown next to the end-margin of my editor. However, I can not type any text in it. When I type something, it jumps off to the emojione-button. See picture a and b:

![click behind editor](https://user-images.githubusercontent.com/33553946/35616712-5e9c75b0-0676-11e8-98e0-b05c6bbe4288.PNG)

![click behind editor b](https://user-images.githubusercontent.com/33553946/35616934-06596f9c-0677-11e8-9fda-2987173baa2d.PNG)

As soon as I type something in the editor itself, this problem vanishes. Does anybody know how to fix that?

Here is my css:

```
 .emojionearea.focused {
            border-color: #66afe9;
            outline: 0;
            -moz-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
            -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
            box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        }

 .emojionearea .emojionearea-editor {
            display: block;
            position: relative;
            height: auto;
            word-break: break-word;
            flex: row wrap;
            white-space: normal;
            padding: 6px 100px 6px 12px;
            font-size: inherit;
            color: white;
            background-color: transparent;
            border: 0;
            cursor: text;
            -moz-border-radius: 0;
            -webkit-border-radius: 0;
            border-radius: 0;
            -moz-box-shadow: none;
            -webkit-box-shadow: none;
            box-shadow: none;
            line-height: normal;
            overflow-x: hidden;
            overflow-y: auto;
        }
```

**Comment by mervick** [comment] 2018-01-31 11:05
Please create example at https://jsfiddle.net/

**Comment by Nixen85** [comment] 2018-01-31 14:04
Sure: https://jsfiddle.net/1v03Lqnu/880/

If you click a bit left around the mic button, you can trigger the described problem...

**Comment by lasdeparq** [comment] 2018-01-31 14:24
@Nixen85 could be the same problem of #76 and #56. Take a look at them.

**Comment by Nixen85** [comment] 2018-01-31 14:56
Thank you - It is the same problem. I now used the suggested bugfix

`.emojionearea-editor:focus::before {
    content: none !important;
}`
Unfortunately, this also clears the placeholder. Any better solution in the future is much appreciated.
Thx!

**Comment by mervick** [comment] 2018-01-31 15:52
I close this because this is duplicate of https://github.com/mervick/emojionearea/issues/76

**Closed by mervick** 2018-01-31 15:52 UTC
