### ISSUE TITLE
how can i insert html content to the textarea?

### ISSUE THREAD

**Issue by qingliangcn** [mervick/emojionearea#49] opened 2016-08-22 13:21 UTC
is there an api to do this? for example:

now the content of textarea is :  👍 hello
then i want to insert this: <img src=xxx/> to the textarea
after that the content is: 👍 hello [image]  to the textarea

the [image] is a real image. 

thanks for your good job.

**Comment by mervick** [comment] 2017-10-04 01:20
duplicate of https://github.com/mervick/emojionearea/issues/22

**Closed by mervick** 2017-10-04 01:20 UTC
Labels: duplicate
