### ISSUE TITLE
call emojioneArea  twice can not return EmojioneArea Object

### ISSUE THREAD

**Issue by GodOfBug2** [mervick/emojionearea#120] opened 2017-04-17 16:19 UTC
$.fn.emojioneArea = function(options) {
        return this.each(function() {
            if (!!this.emojioneArea) return this.emojioneArea;
            $.data(this, 'emojioneArea', this.emojioneArea = new EmojioneArea($(this), options));
            return this.emojioneArea;
        });
    };
Can not return  cache emojioneArea 
$.fn.emojioneArea = function(options) {
    	var dom = this[0];
        if (!!dom.emojioneArea) return dom.emojioneArea;
        $.data(dom, 'emojioneArea', dom.emojioneArea = new EmojioneArea($(this), options));
        return dom.emojioneArea;
    };
  

I need to call emojioneArea  for every dom object

**Comment by mervick** [comment] 2017-10-04 01:26
duplicate of https://github.com/mervick/emojionearea/issues/78

**Closed by mervick** 2017-10-04 01:26 UTC
