### ISSUE TITLE
min file rawgit url problem

### ISSUE THREAD

**Issue by badursun** [mervick/emojionearea#424] opened 2021-01-05 12:34 UTC
In this file "dist/emojionearea.min.js" call external url from rawgit but file is not exist.

https://cdn.rawgit.com/yuku-t/jquery-textcomplete/v1.3.4/dist/jquery.textcomplete.js

**Comment by carpii** [comment] 2021-01-05 15:58
Duplicate of #419

**Closed** 2022-01-28 18:08 UTC
