### ISSUE TITLE
When lost focus... image URL appear...

### ISSUE THREAD

**Issue by pascalf22** [mervick/emojionearea#385] opened 2019-12-13 21:45 UTC
Hello !

First of all, thanks a lot for Emojionearea ! I REALLY love it !

I have a question... 

After inserting some emoji, If my field loses focus, all emoji are transformed into URL?

How can i prevent this

here my code :

```
var emojioneAreas = $("#txttest").emojioneArea({
    pickerPosition: "top",
    tonesStyle: "bullet",
    saveEmojisAs: "image"});
```

How can i prevent ?
I want to send the URL to my DB, all seems to work.. But the only problem is that if i click in other places on the page (ex. body) all the emoji in my input are transformed in the URL !

Thanks a lot !
Have a great weekend !

Pascal

**Comment by mervick** [comment] 2019-12-15 23:08
Seems `saveEmojisAs: "image"` was broken

**Comment by mervick** [comment] 2019-12-16 05:37
It does not appear in [v3.3.1](https://github.com/mervick/emojionearea/releases/tag/v3.3.1).
So, you can use that version for temporary fix.

Example: https://jsfiddle.net/mervick/o67se0um/

**Comment by mervick** [comment] 2019-12-16 05:37
Duplicate of https://github.com/mervick/emojionearea/issues/350

**Closed by mervick** 2019-12-16 05:37 UTC
Labels: bug
