### ISSUE TITLE
getText().length returns wrong values

### ISSUE THREAD

**Issue by collimarco** [mervick/emojionearea#99] opened 2017-02-01 13:41 UTC
See the snippet below:

```
  $('#title').data("emojioneArea").on("keyup paste emojibtn.click", function() {
    var length = this.getText().length;
    console.log(length, this.getText());
});
```

When the input is empty it returns 1 instead of 0. 

The numbers it returns are often wrong: an error of +1 or -1 is usually made compared to the actual string length (even without emoji).

**Comment by collimarco** [comment] 2017-02-01 13:47
This is caused by an extra newline returned by `this.getText()`

**Comment by mervick** [comment] 2017-10-04 01:07
duplicate of https://github.com/mervick/emojionearea/issues/34

**Closed by mervick** 2017-10-04 01:07 UTC
Labels: duplicate
