### ISSUE TITLE
Add onLoad event

### ISSUE THREAD

**Issue by himadrinath** [mervick/emojionearea#152] opened 2017-08-29 08:19 UTC
i want to add other buttons with my emoji emojionearea-button inside emojionearea 

like this 

![text](https://user-images.githubusercontent.com/12247490/29811312-a675049a-8cc0-11e7-9e8d-59e18f11af91.png)

**Comment by mervick** [comment] 2017-08-29 08:48
Sorry, currently there is no events for this, I will add new events in new version,
now you can use `setTimeout()` or `setInterval()` function for checking `input` of emojionearea for being ":hidden" and after that add yours buttons,
something like 
```js
$("#emojionearea").emojionearea();
var ready = function(next) {
  var timer = setInterval(function() {
    if ($("#emojionearea").is(":hidden")) {
      clearInterval(timer);
      next();
    }
  }, 200);
};

ready(function() {
   // add your buttons to emojionearea here
});
```

**Comment by himadrinath** [comment] 2017-09-05 15:28
@mervick  thanks 👍

**Comment by carpii** [comment] 2017-10-06 01:16
@mervick I'm trying to find ways I could contribute to emojionearea

How do you envision this event working?

Maybe an event being fired when emojionearea is about to add the smiley/close button 
and the event contains the markup which is about to be added?

The event handler can return the full markup which will then be appended?

Or some other idea?

**Comment by mervick** [comment] 2017-10-06 01:25
this issue id duplicate of https://github.com/mervick/emojionearea/issues/78

**Closed by mervick** 2017-10-06 01:25 UTC
Labels: enhancement, feature

**Comment by mervick** [comment] 2017-10-06 01:27
@carpii if you have a time you can add onLoad event it must be triggered after init function done, myabe here 
https://github.com/mervick/emojionearea/blob/master/src/function/init.js#L544

**Comment by carpii** [comment] 2017-10-06 01:28
@mervick, thanks I will have a play around tomorrow and see how well it works

**Comment by mervick** [comment] 2017-10-06 01:29
@carpii I want to completely rewrite this plugin but I don't have a time to do this

**Comment by carpii** [comment] 2017-10-06 01:30
@mervick I understand. Even in its present state though, its the best I've seen and still helping a lot of people :)

**Comment by mervick** [comment] 2017-10-06 01:33
@carpii I need help with documentation, if you can do it I would be very grateful

**Comment by carpii** [comment] 2017-10-06 01:37
@mervick Ok I'll try to help with that too, but I dont have an in-depth understanding of it yet, only the bits I've used in my project. I'll submit some doc changes over the weekend, and then you can decide if theyre worth committing

**Comment by mervick** [comment] 2017-10-06 01:37
ok

**Comment by carpii** [comment] 2017-10-07 18:33
@mervick does this new onload event need to use the internal trigger/localstorage mechanism?

Since it will only fire once, from what I can see its just a case of calling trigger("onload")

**Comment by mervick** [comment] 2017-10-07 22:06
it will used for users and fire only once per instance
