### ISSUE TITLE
Add a shortcut like Facebook and Whatsapp

### ISSUE THREAD

**Issue by viperaykiri** [mervick/emojionearea#207] opened 2017-11-14 11:50 UTC
Facebook and Whatsapp can also add smilies to the shortcut :) :-). In this library, it can be added as ": smile:". Can I add extra shortcuts?

I do not look in vain I translated it with google translate

**Comment by mervick** [comment] 2017-11-14 17:02
duplicate of https://github.com/mervick/emojionearea/issues/61

**Closed by mervick** 2017-11-14 17:02 UTC
