### ISSUE TITLE
 Removing / Destroying an Instance

### ISSUE THREAD

**Issue by GlauberF** [mervick/emojionearea#330] opened 2019-01-24 11:14 UTC
Which method can I use to remove / destroy an instance ?

**Comment by mervick** [comment] 2019-01-24 11:47
`destroy` method is currently missing

duplicate of https://github.com/mervick/emojionearea/issues/90

**Comment by mervick** [comment] 2019-01-24 11:53
You can try to use this version 
https://github.com/thinkproductivity/emojionearea
there seems destroy method was implemented
I did not tested yet, but in future it can be merged in main repo
https://github.com/thinkproductivity/emojionearea/blob/4b8fa3eacd1132332bafe4566810999f44796656/src/emojionearea.js#L40-L46

**Comment by GlauberF** [comment] 2019-01-24 12:23
@mervick 

Okay and there is some way to re-update, based on text input from another field.

Example I have a textarea where the user is typing something, I want in the other testarea that has its plugin, which it is updating as the user type in the other textarea.

Why the tests I did, once the emojionearea was rendered, I can not change content by direct javascript

**Comment by mervick** [comment] 2019-01-24 12:48
There is method `setText()` https://github.com/mervick/emojionearea#settextstr
and there is explanation how to use methods https://github.com/mervick/emojionearea#methods-usage

Example:
```js
var area = $(".emojiarea").emojioneArea()[0];

$(".textarea").on("keyup", function() {
  area.emojioneArea.setText($(this).val());
});

**Comment by GlauberF** [comment] 2019-01-24 13:01
worked perfectly :)

**Closed** 2019-01-29 10:55 UTC
Labels: duplicate
