### ISSUE TITLE
Show categories after search

### ISSUE THREAD

**Issue by jerryliu1997** [mervick/emojionearea#341] opened 2019-04-08 04:24 UTC
Hi. If I type for a word such as "lemon", and then click lemon emoji, not all the categories are scrollable. but then if I type something else, everything is fine again

**Comment by mervick** [comment] 2019-04-08 05:10
Duplicate of https://github.com/mervick/emojionearea/issues/255

**Closed by mervick** 2019-04-08 05:10 UTC
Labels: bug
