### ISSUE TITLE
How to destory emojionearea on some click event?

### ISSUE THREAD

**Issue by ahexdev1** [mervick/emojionearea#104] opened 2017-02-09 09:34 UTC
I have initialized emojionearea with angualrjs, now i was seeking for some destroy function, so that we can remove emojionearea when not required.

**Comment by luizcarraro** [comment] 2017-04-06 12:15
I am also in need of something like that to use with an EmberJS component. +1

**Comment by Blkc** [comment] 2017-06-05 20:53
Wouldn't $.remove() would do for destroying the component?

**Comment by mervick** [comment] 2017-06-05 21:14
@Blkc unfortunately no

**Comment by mervick** [comment] 2017-10-04 01:14
duplicate of https://github.com/mervick/emojionearea/issues/104

**Closed by mervick** 2017-10-04 01:14 UTC
