### ISSUE TITLE
Some emojis don't work when saving as shortnames

### ISSUE THREAD

**Issue by elomarns** [mervick/emojionearea#276] opened 2018-04-27 08:04 UTC
I'm trying to save the emojis as shortnames, but some of them don't work that way. They're saved as Unicode. Some examples: :joystick:, :dagger: and :spades:.

Here's a demo showing this behaviour: https://jsfiddle.net/3e4zz4yq/

**Comment by mervick** [comment] 2018-04-27 08:11
It's a emojione v3 bug 
see workaround here https://github.com/mervick/emojionearea/issues/263#issuecomment-377509854

Duplicate of https://github.com/mervick/emojionearea/issues/263

Please open issue here https://github.com/emojione/emojione/issues/new

**Comment by elomarns** [comment] 2018-04-27 08:28
Sorry for the duplicate. It seems like an EmojiOne bug indeed, but I've managed to solve it changing 2 functions from EmojiOne Area:

```javascript
function getTemplate(template, unicode, shortname) {
    var imageType = emojione.imageType, imagePath;
    if (imageType=='svg'){
        imagePath = emojione.imagePathSVG;
    } else {
        imagePath = emojione.imagePathPNG;
    }
    var friendlyName = '';
    if (shortname) {
        friendlyName = shortname.substr(1, shortname.length - 2).replace(/_/g, ' ').replace(/\w\S*/g, function(txt) { return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
    }
    var fname = '';
    if (unicode.uc_base && emojioneSupportMode > 4) {
        fname = unicode.uc_base;
        unicode = unicode.uc_output.toUpperCase();
    } else {
        fname = unicode;
    }
    template = template.replace('{name}', shortname || '')
        .replace('{friendlyName}', friendlyName)
        .replace('{img}', imagePath + (emojioneSupportMode < 2 ? fname.toUpperCase() : fname) + '.' + imageType)
        .replace('{uni}', unicode);

    if(shortname) {
      template = template.replace('{alt}', emojione.shortnameToUnicode(shortname));
    } else {
      template = template.replace('{alt}', emojione.convert(unicode));
    }

    return template;
};

function unicodeTo(str, template) {
    return str.replace(uniRegexp, function(unicodeChar) {
        var map = emojione[(emojioneSupportMode === 0 ? 'jsecapeMap' : 'jsEscapeMap')];
        if (typeof unicodeChar !== 'undefined' && unicodeChar in map) {
            return getTemplate(template, map[unicodeChar], emojione.toShort(unicodeChar));
        }
        return unicodeChar;
    });
}
```

On the code above I'm passing the shortname to the function *getTemplate*, avoiding the EmojiOne function *convert*, as it seems the source of errors.

**Comment by mervick** [comment] 2018-04-27 08:38
Please create PR, so it can be solved for EmojioneArea

**Comment by elomarns** [comment] 2018-04-27 08:47
I will. I'm just trying to test properly to avoid any breaks before creating a PR.

**Closed** 2018-05-09 20:16 UTC
Labels: duplicate, emojione-bug
