### ISSUE TITLE
append textarea in success AJAX - works very slowly

### ISSUE THREAD

**Issue by flicly** [mervick/emojionearea#174] opened 2017-10-24 20:32 UTC
Hello,
I have a problem, namely when adding content in AJAX with append, emojionearea works very slowly, no matter how I did not refer to it, how to fix this?

PS. For every AJAX request I do not know why, but emojionearea reloads something and the page is lag again.

Thank you.

**Comment by carpii** [comment] 2017-10-24 20:34
Provide some test code... https://jsfiddle.net/1v03Lqnu/

Your question is too vague

**Comment by mervick** [comment] 2017-10-24 20:35
Can you show your network requests from dev-tools ?

**Comment by flicly** [comment] 2017-10-24 20:52
![image](https://user-images.githubusercontent.com/28869511/31966805-293c6432-b90c-11e7-8b32-0760548f7f9b.png)

@carpii This is only example

```
$.ajax({
  	type : 'POST',
    dataType : 'json',
    ...
    
    success :
      $.each(xhr, function(i, ob){
		$('#mydiv').append('/*other content...*/<textarea id="comment"></textarea>');
				
       $('#comment').emojionearea({
        	pickerPosition		: 'top',
		tones			: true,
		tonesStyle        : 'bullet',
		autoHideFilters   : true,
		saveEmojisAs		: 'shortname',
		autocomplete 		: false
        });
      }
  });
```

**Comment by mervick** [comment] 2017-10-24 20:56
You have these requests after each AJAX?

**Comment by mervick** [comment] 2017-10-24 20:57
I see emojionearea.js, so probably it's a first request. If not, so you load emojionearea each request

**Comment by mervick** [comment] 2017-10-24 21:00
Load your page click "clear" on your network tab in dev-tools, and when make your AJAX request, after what share requests what make emojionearea after AJAX

**Comment by carpii** [comment] 2017-10-24 21:00
@flicly Im not sure but it seems like you are appending anew textarea each time, but with the id of "#comment", and then converting that to EmojiOneArea?

#id has to be unique in a document. Maybe you are building up duplicates?

**Comment by flicly** [comment] 2017-10-24 21:04
@mervick No, after another request nothing will change, except that the page is lag.
@carpii no, my mistake there was to be ".comment" not "#comment"

**Comment by carpii** [comment] 2017-10-24 21:12
> @carpii no, my mistake there was to be ".comment" not "#comment"

Can you post accurate code? 

After the ajax has completed, have you inspected the DOM around the EmojiOneArea, to make sure its as you expect?

**Comment by mervick** [comment] 2017-10-24 21:25
probably because you are creating new emojioneareas for all prev editors too:
I believe this will solve your problem:
```js
$.ajax({
    type : 'POST',
    dataType : 'json',
    ...
    success :
      $.each(xhr, function(i, ob){
        var mydiv = $('#mydiv');
        mydiv.append('/*other content...*/<textarea class="comment"></textarea>');

        mydiv.search('.comment').emojionearea({
            pickerPosition      : 'top',
            tones           : true,
            tonesStyle        : 'bullet',
            autoHideFilters   : true,
            saveEmojisAs        : 'shortname',
            autocomplete        : false
        });
      }
  });
```

**Comment by mervick** [comment] 2017-10-24 21:37
updated previous comment, was an error in code

**Comment by flicly** [comment] 2017-10-24 21:38
@mervick **search**, maybe **find**? Because **search** is not work and **find** nothing changed.

**Comment by mervick** [comment] 2017-10-24 21:38
sorry, yes you are right

**Comment by mervick** [comment] 2017-10-24 21:43
ok, can you add this in your AJAX
```js
        var content = $("<div/>");
        content.html('/*other content...*/<textarea class="comment"></textarea>');
        $('#mydiv').append(content);
        var emojioneareas = content.find('.comment');
        console.log("count", emojioneareas.length);
        emojioneareas.emojionearea({ /* ... *// });
```

**Comment by flicly** [comment] 2017-10-24 22:02
@mervick found ".comment" (displayed only once despite subsequent requests), but still the same problem.

**Comment by flicly** [comment] 2017-10-24 22:04
When emojionearea adds to the static element everything works fine with only the problem is with AJAX :/

**Comment by mervick** [comment] 2017-10-24 22:07
please reproduce your issue in example [here](https://jsfiddle.net/) with code similar to yours

**Comment by flicly** [comment] 2017-10-24 22:14
Full code AJAX: https://jsfiddle.net/b7oLng8p/

**Comment by mervick** [comment] 2017-10-24 22:17
it's empty frame

**Comment by flicly** [comment] 2017-10-24 22:19
@mervick  **js** frame is empty?

**Comment by mervick** [comment] 2017-10-24 22:20
I don't need your code, only working example with similar code which reproduces your issue

>  @mervick js frame is empty?

working example https://jsfiddle.net/1v03Lqnu/12/

**Comment by flicly** [comment] 2017-10-24 22:37
@mervick I think this is due to AJAX request delays, maybe as I go from localhost to the server then the load speed will be improved.

**Comment by carpii** [comment] 2017-10-24 22:41
@flicly I think at this point you should consider scattering some console.log() calls in your code, and try to see what is going on. 
Chrome also has a javascript debugger which would no doubt help. Youcan also type jQuery commands into console, such as $(".comment").length

**Comment by mervick** [comment] 2017-10-24 22:44
probably it's not an emojionearea issue, so I close this

**Closed by mervick** 2017-10-24 22:44 UTC
