### ISSUE TITLE
Using with tinymce editor

### ISSUE THREAD

**Issue by ashish-mittal-quovantis** [mervick/emojionearea#280] opened 2018-05-17 09:47 UTC
Is there any way to work with emojione area and tinymce editor together ?

**Comment by lasdeparq** [comment] 2018-05-17 11:25
I suggest you to use standalone version and then treat the click in some emoji in picker to insert in your editor.

**Comment by ashish-mittal-quovantis** [comment] 2018-05-18 05:25
yes it will work but when i pick any emoji it closes automatically. It is not remain open like without standalone version.

**Comment by lasdeparq** [comment] 2018-05-18 11:10
@ashish-mittal-quovantis just set  hidePickerOnBlur: false in options

**Comment by ashish-mittal-quovantis** [comment] 2018-05-23 09:03
Thanks for the help..Its working now.

**Comment by harshal-shirude** [comment] 2018-08-22 05:34
Is there workaround to make it happen? I investigated it alot and most of the posts says I will have to write entire custom plugin which will work similar way emojiOne-area works.

**Comment by mervick** [comment] 2018-12-05 22:01
duplicate of https://github.com/mervick/emojionearea/issues/235

**Closed by mervick** 2018-12-05 22:01 UTC
