### ISSUE TITLE
Instant Replace Text Smiley

### ISSUE THREAD

**Issue by divdax** [mervick/emojionearea#123] opened 2017-04-26 09:21 UTC
Hey!

It is possible to instantly replace text smilies e.g. ```:)```, ```;)```, ```:p``` to emoji icon while typing like facebook does?

**Comment by mervick** [comment] 2017-04-26 12:42
Hi,
Probably it possible, but for that need to review emojionearea code and add additional optioins/code

**Comment by mike3run** [comment] 2017-05-03 16:46
with some `string.replace` and a regex possibly on the `keyup` event

**Comment by mervick** [comment] 2017-10-04 01:33
Duplicate of https://github.com/mervick/emojionearea/issues/61

**Closed by mervick** 2017-10-04 01:33 UTC
Labels: enhancement
