### ISSUE TITLE
The getText () method does not correctly (Textarea gets more hyphens than actually)

### ISSUE THREAD

**Issue by omirali** [mervick/emojionearea#144] opened 2017-07-21 10:09 UTC
The getText () method does not correctly calculate the number of line breaks after they have been deleted,
That is, when you add a line break, the first time everything is fine, but after removing the line breaks and adding again, extra line breaks appear.
Example:
We type a few characters -> create 3 new lines (enter button) -> delete these line breaks and reinsert several hyphens
Open the source code and see the extra hyphenation in textarea

`keyup: function (editor, event) {	  `
`		    var text = this.getText();`
`			var lines = text.split(/\n/);`
`			var lineCount = lines.length;`
`			console.log('line count:'+lineCount);`
 `         },`

**Comment by mervick** [comment] 2017-07-21 17:37
It happens because the contenteditable inserts new lines on different ways in different browsers.
There are a lot of combinations of `<div>`, `<br>` and `<p>`.
In past it was remove some new lines, so I decide to add extra new line in cases when it is not clear to remove or leave.

**Comment by omirali** [comment] 2017-07-24 03:09
Prompt, where exactly to remove superfluous line breaks (Only for our project). Thank you and sorry for my english )

**Comment by mervick** [comment] 2017-07-24 10:09
Your english is ok.
I don't know how to fix this, you can try to change these regular expressions for you project
https://github.com/mervick/emojionearea/blob/master/src/function/textFromHtml.js#L10-L24

**Comment by mervick** [comment] 2017-07-24 10:23
For build project see this https://github.com/mervick/emojionearea#building

**Comment by mervick** [comment] 2017-10-04 00:55
duplicate of https://github.com/mervick/emojionearea/issues/34

**Closed by mervick** 2017-10-04 00:55 UTC
Labels: bug, help wanted
