### ISSUE TITLE
emojionearea with wysiwyg editor

### ISSUE THREAD

**Issue by Pok4** [mervick/emojionearea#446] opened 2022-03-17 14:22 UTC
Hi guys,

I want to have some bbcodes for my users in the textarea. For example:
  ['style', ['bold', 'italic', 'underline', ]],
  ['font', ['strikethrough','fontname','clear']]

I want to make textarea compatible with emojionearea and wysiwyg editor.

Can you give me a advice about wysiwyg editor which is compatible with emojionearea or maybe custom example to create my own with this bbcodes above...

I like https://summernote.org/ (summer note wysiwyg editor) and i'll be very happy if emojionearea is compatible with this editor...

Thank you for any replies in advance :)

**Comment by anamauad** [comment] 2022-04-12 00:34
Maybe this issue is a duplicate of #220

**Comment by anamauad** [comment] 2022-04-12 13:46
> summernote
> Hi! Thank you, but this is not what i want. I want to integrate emojionearea with wysiwyg editor like summernote.

It seems you want summernote to add emoji support.

You can verify this at their github:
https://github.com/summernote/summernote/issues/638

Take a look at summernote plugins: 
https://github.com/summernote/awesome-summernote

**Closed** 2022-04-18 15:07 UTC
