### ISSUE TITLE
getText() removes line breaks from text

### ISSUE THREAD

**Issue by akudryav** [mervick/emojionearea#85] opened 2016-12-29 19:54 UTC
When I use 
`$('#message').data("emojioneArea").getText()`
it returns text without line breaks. How could I avoid this?

**Comment by mervick** [comment] 2016-12-30 12:37
It happens, because in some cases this functions works not correctly,
[textFromHtml](https://github.com/mervick/emojionearea/blob/master/src/function/textFromHtml.js)
[htmlFromText](https://github.com/mervick/emojionearea/blob/master/src/function/htmlFromText.js)

**Comment by dowrow** [comment] 2017-01-30 23:13
This should be marked as critical bug and not as enhancement. This makes this lib practically unusable.

**Comment by webexperto** [comment] 2017-02-01 18:31
I know where make the changes, but I don't know exactly what to change.
How do we solve it?

**Comment by mervick** [comment] 2017-10-04 01:17
duplicate of https://github.com/mervick/emojionearea/issues/34

**Closed by mervick** 2017-10-04 01:17 UTC
Labels: enhancement
